### ISSUE TITLE
Tailwind Viewer doesn't work in 4.0.0/4.0.1

### ISSUE THREAD

**Issue by toxin20** [nuxt-community/tailwindcss-module#297]
### Version
@nuxtjs/tailwindcss: 4.0.1 
nuxt: 2.15.3 
node: 14.15.4
npm: 7.5.4

### Reproduction Link
N/A

### Steps to reproduce
Create a fresh Nuxt project with version 2.15.3 (I used `npm init nuxt-app nuxt-tailwind2-test`). Then follow steps from https://tailwindcss.nuxtjs.org/setup to install TailwindCSS

### What is Expected?
Running `npm run dev` should start the tailwind viewer at http://localhost:3000/_tailwind/

### What is actually happening?
I'm getting the error message `Cannot find module 'tailwindcss/resolveConfig'` when running `npm run dev`. Tailwind CSS compilation and Nuxt dev server works though.

![Bildschirmfoto 2021-03-16 um 11 33 27](https://user-images.githubusercontent.com/123776/111295375-94ad8100-864b-11eb-88a3-b563e3ce06c9.png)

The error doesn't appear if I set `viewer: false` for tailwind in the nuxt.config.js

**Comment by toxin20** [comment]
**Update:** 
This seems to have something to do with npm. I saw that the sandbox was using yarn and I couldn't reproduce the error there. Tried using yarn on my local machine and it worked there as well. 

@Atinux: Would you generally advise against using nuxt with npm? I see in the nuxt docs that yarn is the "first class citizen" shown for the guides and I'm wondering if this is just a matter of taste or if you would advise me to run existing and new nuxt projects with yarn.

**Comment by Atinux** [comment]
Can you tell that when running `npm install tailwindcss` it works?

**Comment by toxin20** [comment]
> Can you tell that when running `npm install tailwindcss` it works?

Yes, then it works. 👍🏻

**Comment by rogden** [comment]
@pi0 Your fix is merged in [v1.5.1](https://github.com/rogden/tailwind-config-viewer/releases/tag/v1.5.1)

**Comment by JakubDmochowski** [comment]
tailwind-config-viewer refers to tailwind's absolute path assuming it is in root folder (node_modules/tailwindcss), while @nuxtjs/tailwind package uses tailwind in subfolder (node_modules/@nuxtjs/tailwindcss)

**Comment by productfrontenddeveloper** [comment]
@Atinux or @toxin20 is it fixed ? Please closed issue :)
